#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pymemcache
Version  : 1.3.4
Release  : 18
URL      : https://pypi.python.org/packages/source/p/pymemcache/pymemcache-1.3.4.tar.gz
Source0  : https://pypi.python.org/packages/source/p/pymemcache/pymemcache-1.3.4.tar.gz
Summary  : A comprehensive, fast, pure Python memcached client
Group    : Development/Tools
License  : Apache-2.0
Requires: pymemcache-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
pymemcache
==========
.. image:: https://travis-ci.org/pinterest/pymemcache.png
:target: https://travis-ci.org/pinterest/pymemcache

%package python
Summary: python components for the pymemcache package.
Group: Default

%description python
python components for the pymemcache package.


%prep
%setup -q -n pymemcache-1.3.4

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
