#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pymemcache
Version  : 2.1.1
Release  : 42
URL      : https://files.pythonhosted.org/packages/84/06/0ba87e4bbbae5c1838120e74cc5df0d901e1b343d7958f2149207b569afd/pymemcache-2.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/84/06/0ba87e4bbbae5c1838120e74cc5df0d901e1b343d7958f2149207b569afd/pymemcache-2.1.1.tar.gz
Summary  : A comprehensive, fast, pure Python memcached client
Group    : Development/Tools
License  : Apache-2.0
Requires: pymemcache-license = %{version}-%{release}
Requires: pymemcache-python = %{version}-%{release}
Requires: pymemcache-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : six

%description
pymemcache
==========
.. image:: https://travis-ci.org/pinterest/pymemcache.svg
:target: https://travis-ci.org/pinterest/pymemcache

%package license
Summary: license components for the pymemcache package.
Group: Default

%description license
license components for the pymemcache package.


%package python
Summary: python components for the pymemcache package.
Group: Default
Requires: pymemcache-python3 = %{version}-%{release}

%description python
python components for the pymemcache package.


%package python3
Summary: python3 components for the pymemcache package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pymemcache package.


%prep
%setup -q -n pymemcache-2.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548730857
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pymemcache
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/pymemcache/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pymemcache/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
